/*
 * Regenerates the Android launcher icon, splash icon and Play Store icon from YipDen_Fox.png (the
 * fox and its howl without the arch, itself derived from YipDen_Logo.webp by fox-only.cjs). See README.md in this folder for
 * what needs installing first (sharp, potrace, svgo — deliberately not project dependencies) and
 * what this does and does not cover.
 */
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');
const potrace = require('potrace');
const { optimize } = require('svgo');

const HERE = __dirname;
const SOURCE = path.join(HERE, 'YipDen_Fox.png');
const RES = path.join(HERE, '../apps/reader/android/app/src/main/res');
const STORE = path.join(HERE, '../apps/reader/store');

// The mark itself (the arch, the fox, the ring, the howl) is a single white shape on transparent,
// so only the background behind it needs a color at all, and that is the one thing that switches
// with the system's day/night mode: brand orange by day, this app's own dark `--ground` by night.
const DAY_BACKGROUND = '#C2410C';
const NIGHT_BACKGROUND = '#120B08';
const MARK_FILL = '#FFFFFF';

// Where the mark is scaled/centered within the 108x108 adaptive icon canvas. A launcher shows the
// middle 72 units through its own mask, a circle at worst; the fox reaches toward two corners (its
// tail, its howl), so at 54 it stays inside that circle on every mask shape (checked 2026-10-02).
const SAFE_ZONE = 54;

// The splash screen icon is masked to the same 72-unit circle, so the size that fits a circular
// launcher fits the splash too, and the two match.
const SPLASH_SIZE = 54;

function trace(pngPath, options) {
	return new Promise((resolve, reject) => {
		potrace.trace(pngPath, options, (err, svg) => (err ? reject(err) : resolve(svg)));
	});
}

function optimizedPath(svg) {
	const result = optimize(svg, {
		multipass: true,
		plugins: [{ name: 'preset-default' }],
		js2svg: { pretty: false },
		floatPrecision: 1
	});
	const d = result.data.match(/<path[^>]*\bd="([^"]+)"/)[1];
	const viewBox = result.data
		.match(/viewBox="([^"]+)"/)[1]
		.split(' ')
		.map(Number);
	return { d, width: viewBox[2], height: viewBox[3] };
}

/** A black-on-white bitmap of the source's own opaque pixels, for potrace. */
async function extractMask({ data, info }) {
	const { width, height, channels } = info;
	const out = Buffer.alloc(width * height).fill(255);
	let minX = width;
	let minY = height;
	let maxX = 0;
	let maxY = 0;
	for (let y = 0; y < height; y += 1) {
		for (let x = 0; x < width; x += 1) {
			const i = (y * width + x) * channels;
			if (data[i + 3] > 128) {
				out[y * width + x] = 0;
				if (x < minX) minX = x;
				if (x > maxX) maxX = x;
				if (y < minY) minY = y;
				if (y > maxY) maxY = y;
			}
		}
	}
	return {
		image: sharp(out, { raw: { width, height, channels: 1 } }),
		bbox: { minX, minY, maxX, maxY }
	};
}

async function cropToContent({ image, bbox }, pad = 20) {
	const meta = await image.metadata();
	const left = Math.max(0, bbox.minX - pad);
	const top = Math.max(0, bbox.minY - pad);
	const width = Math.min(meta.width - left, bbox.maxX - bbox.minX + 2 * pad);
	const height = Math.min(meta.height - top, bbox.maxY - bbox.minY + 2 * pad);
	return image.extract({ left, top, width, height });
}

function backgroundVector(background) {
	return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by brand/generate-icons.cjs from YipDen_Fox.png. See brand/README.md. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="${background}"
        android:pathData="M0,0h108v108h-108z" />
</vector>
`;
}

async function main() {
	const raw = await sharp(SOURCE).raw().ensureAlpha().toBuffer({ resolveWithObject: true });
	const mask = await extractMask(raw);
	const cropped = await cropToContent(mask);
	const small = await cropped.resize(1024).threshold(128).png().toBuffer();

	const mark = optimizedPath(
		await trace(small, { threshold: 128, turdSize: 8, optTolerance: 0.3, alphaMax: 1 })
	);
	fs.writeFileSync(path.join(HERE, 'fox.path.txt'), mark.d);
	console.log(`Traced mark (${mark.width}x${mark.height}).`);
	console.log(
		'Also written to fox.path.txt. The in-app marks keep the arched mark (mark.path.txt).'
	);

	const scale = SAFE_ZONE / Math.max(mark.width, mark.height);
	const w = mark.width * scale;
	const h = mark.height * scale;
	const tx = (108 - w) / 2;
	const ty = (108 - h) / 2;

	function foregroundVector(fill, size = SAFE_ZONE) {
		const s = size / Math.max(mark.width, mark.height);
		const x = (108 - mark.width * s) / 2;
		const y = (108 - mark.height * s) / 2;
		return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by brand/generate-icons.cjs from YipDen_Fox.png. See brand/README.md. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group
        android:translateX="${x.toFixed(3)}"
        android:translateY="${y.toFixed(3)}"
        android:scaleX="${s.toFixed(6)}"
        android:scaleY="${s.toFixed(6)}">
        <path
            android:fillColor="${fill}"
            android:pathData="${mark.d}" />
    </group>
</vector>
`;
	}

	// The background layer carries the day/night color itself (a plain full-bleed fill) through
	// drawable/ vs drawable-night/, rather than a @color resource: an adaptive icon's
	// <background> is one drawable reference, so the day/night split has to live at that level.
	fs.mkdirSync(path.join(RES, 'drawable-night'), { recursive: true });
	fs.writeFileSync(
		path.join(RES, 'drawable/ic_launcher_background.xml'),
		backgroundVector(DAY_BACKGROUND)
	);
	fs.writeFileSync(
		path.join(RES, 'drawable-night/ic_launcher_background.xml'),
		backgroundVector(NIGHT_BACKGROUND)
	);
	fs.writeFileSync(
		path.join(RES, 'drawable/ic_launcher_foreground.xml'),
		foregroundVector(MARK_FILL)
	);
	fs.writeFileSync(
		path.join(RES, 'drawable/ic_launcher_monochrome.xml'),
		foregroundVector('#FF000000')
	);
	fs.writeFileSync(
		path.join(RES, 'drawable/splash_icon.xml'),
		foregroundVector(MARK_FILL, SPLASH_SIZE)
	);

	function flatSvg(background) {
		// The middle 72 units only: what a launcher actually shows of the 108-unit adaptive canvas,
		// so a flat icon (Play Store, pre-Android-8) frames the mark the way a launcher does.
		return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72">
  <rect width="108" height="108" fill="${background}"/>
  <g transform="translate(${tx},${ty}) scale(${scale})"><path d="${mark.d}" fill="${MARK_FILL}"/></g>
</svg>`;
	}

	const densities = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
	for (const [name, size] of Object.entries(densities)) {
		const square = await sharp(Buffer.from(flatSvg(DAY_BACKGROUND)))
			.resize(size, size)
			.png()
			.toBuffer();
		await sharp(square).toFile(path.join(RES, `mipmap-${name}/ic_launcher.png`));
		const circle = Buffer.from(
			`<svg width="${size}" height="${size}"><circle cx="${size / 2}" cy="${size / 2}" r="${size / 2}" fill="#fff"/></svg>`
		);
		await sharp(square)
			.composite([{ input: circle, blend: 'dest-in' }])
			.png()
			.toFile(path.join(RES, `mipmap-${name}/ic_launcher_round.png`));
	}

	fs.mkdirSync(STORE, { recursive: true });
	await sharp(Buffer.from(flatSvg(DAY_BACKGROUND)))
		.resize(512, 512)
		.png()
		.toFile(path.join(STORE, 'play-icon-512.png'));

	console.log(
		'Wrote Android vector drawables (launcher and splash), legacy PNGs, and the Play Store icon.'
	);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
