/**
 * Vendor the app's fonts into the bundle.
 *
 * The app works offline and must not call Google at runtime: a reader on a train should not
 * see a different typeface than a reader at home, and a font request is a request that tells
 * someone else's server which app was opened and when.
 *
 * This downloads the woff2 files once and writes a local stylesheet beside them. It is not
 * part of the build. Run it when a font needs refreshing, and commit the result.
 *
 *   node scripts/vendor-fonts.mjs
 *
 * All three families are SIL Open Font License 1.1. OFL.txt sits beside them.
 */

import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const OUT_DIR = fileURLToPath(new URL('../static/fonts/', import.meta.url));

const GOOGLE_CSS =
	'https://fonts.googleapis.com/css2' +
	'?family=Bricolage+Grotesque:opsz,wght@12..96,400..800' +
	'&family=Instrument+Sans:wght@400..700' +
	'&family=JetBrains+Mono:wght@400;500' +
	'&display=swap';

// A UA modern enough that Google serves woff2 and variable fonts.
const UA =
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ' +
	'Chrome/140.0.0.0 Safari/537.36';

/** Latin and Latin Extended cover the ring's members today, at a fraction of the bytes. */
const WANTED_SUBSETS = ['latin', 'latin-ext'];

function subsetOf(block) {
	const comment = block.match(/\/\*\s*([a-z-]+)\s*\*\//i);
	return comment?.[1] ?? null;
}

function fieldOf(block, name) {
	return block.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1]?.trim() ?? '';
}

function slugOf(family) {
	return family.replace(/['"]/g, '').toLowerCase().replace(/\s+/g, '-');
}

const response = await fetch(GOOGLE_CSS, { headers: { 'user-agent': UA } });
if (!response.ok) throw new Error(`Google Fonts replied ${response.status}`);
const css = await response.text();

// Each @font-face is preceded by a comment naming its subset.
const blocks = css.split('@font-face').slice(1);
const faces = [];
let subset = null;

for (const [index, raw] of blocks.entries()) {
	const preceding = css.split('@font-face')[index] ?? '';
	subset = subsetOf(preceding.slice(-40)) ?? subset;
	if (!WANTED_SUBSETS.includes(subset ?? '')) continue;

	const family = fieldOf(raw, 'font-family').replace(/['"]/g, '');
	const weight = fieldOf(raw, 'font-weight');
	const style = fieldOf(raw, 'font-style') || 'normal';
	const range = fieldOf(raw, 'unicode-range');
	const url = raw.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/)?.[1];
	if (!url || !family) continue;

	const file = `${slugOf(family)}-${subset}-${weight.replace(/\s+/g, '')}.woff2`;
	faces.push({ family, weight, style, range, url, file });
}

await mkdir(OUT_DIR, { recursive: true });

// Google serves one variable file for several declared weights, so the same bytes can arrive
// under several names. Hash them and write each file once.
const byHash = new Map();

for (const face of faces) {
	const data = await fetch(face.url, { headers: { 'user-agent': UA } });
	if (!data.ok) throw new Error(`could not download ${face.file}: ${data.status}`);

	const bytes = Buffer.from(await data.arrayBuffer());
	const hash = createHash('sha256').update(bytes).digest('hex');
	const existing = byHash.get(hash);
	if (existing) {
		face.file = existing;
		console.log(`reused ${existing} for ${face.family} ${face.weight}`);
		continue;
	}

	byHash.set(hash, face.file);
	await writeFile(new URL(face.file, `file://${OUT_DIR}`), bytes);
	console.log(`saved ${face.file} (${(bytes.length / 1024).toFixed(1)}kB)`);
}

const stylesheet = [
	'/*',
	' * Generated by scripts/vendor-fonts.mjs. Do not edit by hand.',
	' *',
	' * Bricolage Grotesque, Instrument Sans and JetBrains Mono, all SIL Open Font License 1.1.',
	' * See OFL.txt beside this file.',
	' */',
	'',
	...faces.map((face) =>
		[
			'@font-face {',
			`\tfont-family: '${face.family}';`,
			`\tfont-style: ${face.style};`,
			`\tfont-weight: ${face.weight};`,
			'\tfont-display: swap;',
			`\tsrc: url('./${face.file}') format('woff2');`,
			`\tunicode-range: ${face.range};`,
			'}',
			''
		].join('\n')
	)
].join('\n');

await writeFile(new URL('fonts.css', `file://${OUT_DIR}`), stylesheet);
console.log(`wrote fonts.css with ${faces.length} faces`);
